package tests;

import static org.hamcrest.CoreMatchers.*;
import static org.hamcrest.MatcherAssert.*;
//import static org.junit.Assert.assertThat;
import static org.junit.Assert.assertTrue;

import java.util.Map;

import org.junit.After;
import org.junit.Before;
//Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import pages.HomePage;
import pages.ProdutoPage;

public class TesteTest
{
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	private HomePage homePage;

	@Before
	public void setUp()
	{
		System.setProperty("webdriver.chrome.driver", "C:\\WebDrivers\\Chrome\\chromedriver.exe");
		driver = new ChromeDriver();
		homePage = new HomePage(driver);
		driver.get("https://marcelodebittencourt.com/demoprestashop/");
		driver.manage().window().maximize();
	}

	@After
	public void tearDown()
	{
		driver.quit();
	}

	@Test
	public void validaTextoContactUs()
	{
		assertThat(homePage.obterTextLinkContactUs(), is("Contact us"));
	}

	@Test
	public void validaNomeProdutoTelaDetalhe_NomesIguais()
	{
		String nomeProdutoHomePage = homePage.obterNomePrimeiroProduto();
		System.out.println(nomeProdutoHomePage);
		
		ProdutoPage produtoPage = homePage.clicarNomePrimeiroProduto();
		String nomeProduto = produtoPage.obterNomeProduto();
		System.out.println(nomeProduto);
		
		assertThat(nomeProdutoHomePage.toLowerCase(),is (nomeProduto.toLowerCase()));
		assertThat(nomeProdutoHomePage.toUpperCase(),is (nomeProduto.toUpperCase()));
	}
}
